# version: '3.8'

services:
  backend:
    build: .
    container_name: event_backend
    command: npm run start:dev
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - .env
    # depends_on:
    # - event_db
volumes:
  postgres_data:
