export const PermissionCode = {
  USER_VIEW: 'USER_VIEW',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',

  ORGANIZATION_VIEW: 'ORGANIZATION_VIEW',
  ORGANIZATION_CREATE: 'ORGANIZATION_CREATE',
  ORGANIZATION_UPDATE: 'ORGANIZATION_UPDATE',
  ORGANIZATION_DELETE: 'ORGANIZATION_DELETE',
  ORGANIZATION_VERIFY: 'ORGANIZATION_VERIFY',
  ORGANIZATION_MEMBER_MANAGE: 'ORGANIZATION_MEMBER_MANAGE',

  EVENT_VIEW: 'EVENT_VIEW',
  EVENT_CREATE: 'EVENT_CREATE',
  EVENT_UPDATE: 'EVENT_UPDATE',
  EVENT_DELETE: 'EVENT_DELETE',
  EVENT_MANAGE: 'EVENT_MANAGE',

  TICKET_VIEW: 'TICKET_VIEW',
  TICKET_CREATE: 'TICKET_CREATE',
  TICKET_UPDATE: 'TICKET_UPDATE',
  TICKET_MANAGE: 'TICKET_MANAGE',

  ROLE_VIEW: 'ROLE_VIEW',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',

  PERMISSION_VIEW: 'PERMISSION_VIEW',
  PERMISSION_CREATE: 'PERMISSION_CREATE',
  PERMISSION_UPDATE: 'PERMISSION_UPDATE',
  PERMISSION_DELETE: 'PERMISSION_DELETE',

  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_CREATE: 'REPORT_CREATE',
  REPORT_UPDATE: 'REPORT_UPDATE',
  REPORT_DELETE: 'REPORT_DELETE',

  VERIFICATION_VIEW: 'VERIFICATION_VIEW',
  VERIFICATION_APPROVE: 'VERIFICATION_APPROVE',
  VERIFICATION_REJECT: 'VERIFICATION_REJECT',

  INVITATION_VIEW: 'INVITATION_VIEW',
  INVITATION_CREATE: 'INVITATION_CREATE',
  INVITATION_UPDATE: 'INVITATION_UPDATE',
  INVITATION_DELETE: 'INVITATION_DELETE',

  DASHBOARD_VIEW: 'DASHBOARD_VIEW',

  UPLOAD_CREATE: 'UPLOAD_CREATE',

  CATEGORY_VIEW: 'CATEGORY_VIEW',
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_UPDATE: 'CATEGORY_UPDATE',
  CATEGORY_DELETE: 'CATEGORY_DELETE',
} as const;

export type PermissionCodeValue =
  (typeof PermissionCode)[keyof typeof PermissionCode];

